spring.application.name=ms-notification

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=123
rabbitmq.queue.name=notification-queue
rabbitmq.exchange.name=transfer-exchange
rabbitmq.routing.key.notification=notification.routing.key

logging.level.com.kau4dev.notification=INFO

server.port=8084

