### Criar usuário com CPF válido
POST http://localhost:8081/users
Content-Type: application/json

{
  "fullName": "joao victor",
  "cpf": "12345678909",
  "email": "joaosjd@gmail.com",
  "password": "123467@jao",
  "type": "COMMON"
}

### Criar usuário com CNPJ válido
POST http://localhost:8081/users
Content-Type: application/json

{
  "fullName": "Empresa Teste LTDA",
  "cnpj": "11222333000181",
  "email": "empresa@teste.com",
  "password": "senha123",
  "type": "MERCHANT"
}

### Listar todos os usuários
GET http://localhost:8081/users

### Buscar usuário por ID (substitua pelo ID retornado)
GET http://localhost:8081/users/SEU-UUID-AQUI

